version: 2

project_name: major

before:
  hooks: [go mod tidy]

builds:
  - id: major
    main: .
    binary: major
    env: [CGO_ENABLED=0]
    flags: [-trimpath]
    ldflags:
      - -s -w
      - -X github.com/major-technology/cli/cmd.version={{.Version}}
      - -X github.com/major-technology/cli/cmd.configFile=configs/prod.json
    goos: [darwin, linux]
    goarch: [amd64, arm64]

archives:
  - formats: [tar.gz]     # <- v2 syntax
    files:
      - LICENSE
      - README.md

brews:                     # <- still deprecated but works
  - name: major
    description: "Major CLI"
    homepage: "https://github.com/major-technology/major"
    license: "MIT"
    repository:
      owner: major-technology
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaser
      email: goreleaser@users.noreply.github.com
    test: |
      system "#{bin}/major", "--version"
    install: |
      bin.install "major"

release:
  github:
    owner: major-technology
    name: cli
